version: '3.7'
services:
  pg-dev:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: menutize
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  admin:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  pgdata: