version: '3.7'
services:
  pg-dev:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: menutize
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  admin:
    image: adminer
    ports:
      - "8080:8080"
  angular:
    build: angular
    ports:
      - "4200:4200"
    links:
      - nest
    volumes:
      - ./angular:/app
      - angular_modules:/app/node_modules/
  nest:
    build: server
    ports:
      - "3000:3000"
    links:
      - pg-dev
    volumes:
      - ./server:/usr/src/app
      - nest_modules:/usr/src/app/node_modules/
volumes:
  pgdata:
  angular_modules:
  nest_modules: